/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package cs311_finalexam_nguyenanhtuan;
import java.util.ArrayList;
import java.util.Collections;
import javax.swing.JFileChooser;
import javax.swing.JOptionPane;
import javax.swing.table.DefaultTableModel;

/**
 *
 * @author tuana
 */
public class QLKS extends javax.swing.JFrame {
      DefaultTableModel kb;
      DanhSachKhachHang x = new DanhSachKhachHang();
      ArrayList<KhachHang> a = new ArrayList<KhachHang>();
      ArrayList<KhachHang> b = new ArrayList<KhachHang>();
      ArrayList<KhachHang> c = new ArrayList<KhachHang>();
    public QLKS() {
        initComponents();
        this.setLocationRelativeTo(null);
        rbtSingleRoom.setVisible(true);
        rbtDoubleRoom.setVisible(true);
        rbtTwinRoom.setVisible(true);
        rbtTripleRoom.setVisible(true);
        rbtQuadRoom.setVisible(true);
        rbtdichVu.setVisible(true);
        rbtbinhThuong.setVisible(true);
        rbtcaoCap.setVisible(true);
        btnTang.setVisible(false);
        btnGiam.setVisible(false);
        kb =new  DefaultTableModel();
       
        kb.setColumnIdentifiers(new Object []{"Mã Định Danh","Họ Tên","GT","Quê Quán","SL","Ngày Đến","Ngày Đi","Dịch Vụ","Loại Phòng","ĐG","Tính TT"});
        tblhienThi.setModel(kb);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        buttonGroup1 = new javax.swing.ButtonGroup();
        buttonGroup2 = new javax.swing.ButtonGroup();
        jLabel9 = new javax.swing.JLabel();
        buttonGroup3 = new javax.swing.ButtonGroup();
        jButton6 = new javax.swing.JButton();
        jLabel3 = new javax.swing.JLabel();
        lblmaDinhDanh = new javax.swing.JLabel();
        txtmaDinhDanh = new javax.swing.JTextField();
        lblhoTen = new javax.swing.JLabel();
        txthoTen = new javax.swing.JTextField();
        rbtnam = new javax.swing.JRadioButton();
        jLabel5 = new javax.swing.JLabel();
        txtqueQuan = new javax.swing.JTextField();
        jLabel6 = new javax.swing.JLabel();
        txtngayDen = new javax.swing.JTextField();
        jLabel7 = new javax.swing.JLabel();
        txtngayDi = new javax.swing.JTextField();
        rbtbinhThuong = new javax.swing.JRadioButton();
        rbtcaoCap = new javax.swing.JRadioButton();
        rbtSingleRoom = new javax.swing.JRadioButton();
        rbtDoubleRoom = new javax.swing.JRadioButton();
        rbtTwinRoom = new javax.swing.JRadioButton();
        rbtQuadRoom = new javax.swing.JRadioButton();
        rbtTripleRoom = new javax.swing.JRadioButton();
        jScrollPane1 = new javax.swing.JScrollPane();
        tblhienThi = new javax.swing.JTable();
        lblsoLuong = new javax.swing.JLabel();
        txtsoLuong = new javax.swing.JTextField();
        rbtnu = new javax.swing.JRadioButton();
        lbldonGia = new javax.swing.JLabel();
        txtdonGia = new javax.swing.JTextField();
        btntongTienDichVu = new javax.swing.JButton();
        btntongTienThuePhong = new javax.swing.JButton();
        btndocFile = new javax.swing.JButton();
        btncapNhat = new javax.swing.JButton();
        btnluu = new javax.swing.JButton();
        btnxoa = new javax.swing.JButton();
        btnthoat = new javax.swing.JButton();
        btnsapXep = new javax.swing.JButton();
        rbtdichVu = new javax.swing.JButton();
        rbtloaiPhong = new javax.swing.JButton();
        rbtgioiTinh = new javax.swing.JButton();
        btnGiam = new javax.swing.JButton();
        btnTang = new javax.swing.JButton();
        jButton1 = new javax.swing.JButton();

        jLabel9.setFont(new java.awt.Font("Segoe UI", 0, 18)); // NOI18N
        jLabel9.setText("Mã Định Danh");

        jButton6.setText("ĐỌC FILE");

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setTitle("Quản Lí Khách Hàng");
        setBackground(new java.awt.Color(255, 255, 255));

        jLabel3.setBackground(new java.awt.Color(255, 64, 96));
        jLabel3.setFont(new java.awt.Font("Segoe UI", 1, 24)); // NOI18N
        jLabel3.setForeground(new java.awt.Color(255, 102, 102));
        jLabel3.setText("Quản Lý Khách Hàng Khách Sạn MOMO");
        jLabel3.setToolTipText("");
        jLabel3.setBorder(javax.swing.BorderFactory.createTitledBorder(null, "", javax.swing.border.TitledBorder.DEFAULT_JUSTIFICATION, javax.swing.border.TitledBorder.DEFAULT_POSITION, new java.awt.Font("Segoe UI", 0, 12), new java.awt.Color(153, 0, 153))); // NOI18N

        lblmaDinhDanh.setFont(new java.awt.Font("Segoe UI", 0, 18)); // NOI18N
        lblmaDinhDanh.setText("Mã Định Danh");

        lblhoTen.setFont(new java.awt.Font("Segoe UI", 0, 18)); // NOI18N
        lblhoTen.setText("Họ Tên");

        rbtnam.setBackground(new java.awt.Color(255, 255, 255));
        buttonGroup1.add(rbtnam);
        rbtnam.setFont(new java.awt.Font("Segoe UI", 0, 15)); // NOI18N
        rbtnam.setText("Nam");
        rbtnam.setBorder(new javax.swing.border.LineBorder(new java.awt.Color(255, 204, 204), 1, true));
        rbtnam.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                rbtnamActionPerformed(evt);
            }
        });

        jLabel5.setFont(new java.awt.Font("Segoe UI", 0, 18)); // NOI18N
        jLabel5.setText("Quê Quán");

        txtqueQuan.setMinimumSize(new java.awt.Dimension(64, 28));

        jLabel6.setFont(new java.awt.Font("Segoe UI", 0, 18)); // NOI18N
        jLabel6.setText("Ngày Đến");

        txtngayDen.setMinimumSize(new java.awt.Dimension(64, 28));

        jLabel7.setFont(new java.awt.Font("Segoe UI", 0, 18)); // NOI18N
        jLabel7.setText("Ngày Đi");

        txtngayDi.setMinimumSize(new java.awt.Dimension(64, 28));

        rbtbinhThuong.setBackground(new java.awt.Color(153, 153, 255));
        buttonGroup2.add(rbtbinhThuong);
        rbtbinhThuong.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        rbtbinhThuong.setText("Bình Thường");

        rbtcaoCap.setBackground(new java.awt.Color(153, 153, 255));
        buttonGroup2.add(rbtcaoCap);
        rbtcaoCap.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        rbtcaoCap.setText("Cao Cấp");

        rbtSingleRoom.setBackground(new java.awt.Color(255, 102, 255));
        buttonGroup3.add(rbtSingleRoom);
        rbtSingleRoom.setText("Single Room");

        rbtDoubleRoom.setBackground(new java.awt.Color(255, 102, 255));
        buttonGroup3.add(rbtDoubleRoom);
        rbtDoubleRoom.setText("Double Room");

        rbtTwinRoom.setBackground(new java.awt.Color(255, 102, 255));
        buttonGroup3.add(rbtTwinRoom);
        rbtTwinRoom.setText("Twin Room");

        rbtQuadRoom.setBackground(new java.awt.Color(255, 102, 255));
        buttonGroup3.add(rbtQuadRoom);
        rbtQuadRoom.setText("Quad Room");

        rbtTripleRoom.setBackground(new java.awt.Color(255, 102, 255));
        buttonGroup3.add(rbtTripleRoom);
        rbtTripleRoom.setText("Triple Room");

        tblhienThi.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null}
            },
            new String [] {
                "Title 1", "Title 2", "Title 3", "Title 4"
            }
        ));
        jScrollPane1.setViewportView(tblhienThi);

        lblsoLuong.setFont(new java.awt.Font("Segoe UI", 0, 15)); // NOI18N
        lblsoLuong.setText("Số Lượng");

        txtsoLuong.setFont(new java.awt.Font("Segoe UI", 0, 15)); // NOI18N

        rbtnu.setBackground(new java.awt.Color(255, 255, 255));
        buttonGroup1.add(rbtnu);
        rbtnu.setFont(new java.awt.Font("Segoe UI", 0, 15)); // NOI18N
        rbtnu.setSelected(true);
        rbtnu.setText("Nữ");
        rbtnu.setBorder(new javax.swing.border.LineBorder(new java.awt.Color(255, 204, 204), 1, true));
        rbtnu.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                rbtnuActionPerformed(evt);
            }
        });

        lbldonGia.setFont(new java.awt.Font("Segoe UI", 0, 15)); // NOI18N
        lbldonGia.setText("Đơn Giá");

        txtdonGia.setFont(new java.awt.Font("Segoe UI", 0, 15)); // NOI18N

        btntongTienDichVu.setFont(new java.awt.Font("Segoe UI Black", 0, 14)); // NOI18N
        btntongTienDichVu.setForeground(new java.awt.Color(255, 51, 51));
        btntongTienDichVu.setText("TỔNG TIỀN DỊCH VỤ");
        btntongTienDichVu.setBorder(new javax.swing.border.SoftBevelBorder(javax.swing.border.BevelBorder.RAISED));
        btntongTienDichVu.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btntongTienDichVuActionPerformed(evt);
            }
        });

        btntongTienThuePhong.setFont(new java.awt.Font("Segoe UI Black", 0, 14)); // NOI18N
        btntongTienThuePhong.setForeground(new java.awt.Color(255, 51, 51));
        btntongTienThuePhong.setText("TỔNG TIỀN THUÊ ");
        btntongTienThuePhong.setBorder(new javax.swing.border.SoftBevelBorder(javax.swing.border.BevelBorder.RAISED));
        btntongTienThuePhong.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btntongTienThuePhongActionPerformed(evt);
            }
        });

        btndocFile.setText("ĐỌC FILE");
        btndocFile.setBorder(new javax.swing.border.SoftBevelBorder(javax.swing.border.BevelBorder.RAISED));
        btndocFile.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btndocFileActionPerformed(evt);
            }
        });

        btncapNhat.setText("CẬP NHẬT");
        btncapNhat.setBorder(new javax.swing.border.SoftBevelBorder(javax.swing.border.BevelBorder.RAISED));
        btncapNhat.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btncapNhatActionPerformed(evt);
            }
        });

        btnluu.setText("LƯU");
        btnluu.setBorder(new javax.swing.border.SoftBevelBorder(javax.swing.border.BevelBorder.RAISED));
        btnluu.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnluuActionPerformed(evt);
            }
        });

        btnxoa.setText("LÀM MỚI");
        btnxoa.setBorder(new javax.swing.border.SoftBevelBorder(javax.swing.border.BevelBorder.RAISED));
        btnxoa.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnxoaActionPerformed(evt);
            }
        });

        btnthoat.setFont(new java.awt.Font("Segoe UI Black", 1, 12)); // NOI18N
        btnthoat.setForeground(new java.awt.Color(102, 102, 255));
        btnthoat.setText("THOÁT");
        btnthoat.setBorder(new javax.swing.border.SoftBevelBorder(javax.swing.border.BevelBorder.RAISED));
        btnthoat.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnthoatActionPerformed(evt);
            }
        });

        btnsapXep.setText("SẮP XẾP");
        btnsapXep.setBorder(new javax.swing.border.SoftBevelBorder(javax.swing.border.BevelBorder.RAISED));
        btnsapXep.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnsapXepActionPerformed(evt);
            }
        });

        rbtdichVu.setFont(new java.awt.Font("Segoe UI", 0, 18)); // NOI18N
        rbtdichVu.setText("Dịch Vụ");
        rbtdichVu.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                rbtdichVuActionPerformed(evt);
            }
        });

        rbtloaiPhong.setFont(new java.awt.Font("Segoe UI", 0, 18)); // NOI18N
        rbtloaiPhong.setText("Loại Phòng");
        rbtloaiPhong.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                rbtloaiPhongActionPerformed(evt);
            }
        });

        rbtgioiTinh.setFont(new java.awt.Font("Segoe UI", 0, 18)); // NOI18N
        rbtgioiTinh.setText("Giới Tính");
        rbtgioiTinh.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                rbtgioiTinhActionPerformed(evt);
            }
        });

        btnGiam.setText("GIẢM DẦN");
        btnGiam.setBorder(new javax.swing.border.SoftBevelBorder(javax.swing.border.BevelBorder.RAISED));
        btnGiam.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnGiamActionPerformed(evt);
            }
        });

        btnTang.setText("TĂNG DẦN");
        btnTang.setBorder(new javax.swing.border.SoftBevelBorder(javax.swing.border.BevelBorder.RAISED));
        btnTang.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnTangActionPerformed(evt);
            }
        });

        jButton1.setIcon(new javax.swing.ImageIcon("D:\\ABCD\\Hotel-Flat-icon (1).png")); // NOI18N
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addContainerGap()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(rbtloaiPhong)
                            .addGroup(layout.createSequentialGroup()
                                .addGap(206, 206, 206)
                                .addComponent(rbtTripleRoom)
                                .addGap(44, 44, 44)
                                .addComponent(rbtQuadRoom))))
                    .addGroup(layout.createSequentialGroup()
                        .addContainerGap()
                        .addComponent(rbtdichVu)
                        .addGap(55, 55, 55)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(rbtbinhThuong, javax.swing.GroupLayout.PREFERRED_SIZE, 109, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(18, 18, 18)
                                .addComponent(rbtcaoCap, javax.swing.GroupLayout.PREFERRED_SIZE, 107, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(rbtSingleRoom)
                                .addGap(18, 18, 18)
                                .addComponent(rbtDoubleRoom)
                                .addGap(18, 18, 18)
                                .addComponent(rbtTwinRoom))))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(23, 23, 23)
                        .addComponent(lblsoLuong)
                        .addGap(18, 18, 18)
                        .addComponent(txtsoLuong, javax.swing.GroupLayout.PREFERRED_SIZE, 55, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(24, 24, 24)
                        .addComponent(lbldonGia, javax.swing.GroupLayout.PREFERRED_SIZE, 63, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(18, 18, 18)
                        .addComponent(txtdonGia, javax.swing.GroupLayout.PREFERRED_SIZE, 55, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addGap(97, 97, 97)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addComponent(btntongTienDichVu, javax.swing.GroupLayout.DEFAULT_SIZE, 155, Short.MAX_VALUE)
                            .addComponent(btntongTienThuePhong, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                        .addGap(44, 44, 44)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addComponent(btndocFile, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(btncapNhat, javax.swing.GroupLayout.PREFERRED_SIZE, 135, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(40, 40, 40)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(btnluu, javax.swing.GroupLayout.PREFERRED_SIZE, 135, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(btnsapXep, javax.swing.GroupLayout.PREFERRED_SIZE, 135, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(32, 32, 32)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addComponent(btnGiam, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(btnTang, javax.swing.GroupLayout.PREFERRED_SIZE, 129, javax.swing.GroupLayout.PREFERRED_SIZE)))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(536, 536, 536)
                        .addComponent(btnxoa, javax.swing.GroupLayout.PREFERRED_SIZE, 135, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(layout.createSequentialGroup()
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addGroup(layout.createSequentialGroup()
                                        .addGap(20, 20, 20)
                                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                            .addComponent(jLabel5, javax.swing.GroupLayout.PREFERRED_SIZE, 123, javax.swing.GroupLayout.PREFERRED_SIZE)
                                            .addComponent(jLabel6, javax.swing.GroupLayout.PREFERRED_SIZE, 123, javax.swing.GroupLayout.PREFERRED_SIZE)
                                            .addComponent(jLabel7, javax.swing.GroupLayout.PREFERRED_SIZE, 123, javax.swing.GroupLayout.PREFERRED_SIZE)))
                                    .addGroup(layout.createSequentialGroup()
                                        .addContainerGap()
                                        .addComponent(rbtgioiTinh)))
                                .addGap(23, 23, 23))
                            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                                .addGap(12, 12, 12)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                    .addComponent(lblmaDinhDanh, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                    .addComponent(lblhoTen, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                                .addGap(28, 28, 28)))
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(txtngayDi, javax.swing.GroupLayout.PREFERRED_SIZE, 151, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(txtngayDen, javax.swing.GroupLayout.PREFERRED_SIZE, 151, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(txtqueQuan, javax.swing.GroupLayout.PREFERRED_SIZE, 151, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(rbtnam, javax.swing.GroupLayout.PREFERRED_SIZE, 64, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(18, 18, 18)
                                .addComponent(rbtnu, javax.swing.GroupLayout.PREFERRED_SIZE, 64, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addComponent(txthoTen, javax.swing.GroupLayout.PREFERRED_SIZE, 151, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(txtmaDinhDanh, javax.swing.GroupLayout.PREFERRED_SIZE, 151, javax.swing.GroupLayout.PREFERRED_SIZE)))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(20, 20, 20)
                        .addComponent(jButton1, javax.swing.GroupLayout.PREFERRED_SIZE, 169, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(51, 51, 51)
                        .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 926, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addContainerGap(15, Short.MAX_VALUE))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(163, 163, 163)
                        .addComponent(jLabel3)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(btnthoat, javax.swing.GroupLayout.PREFERRED_SIZE, 110, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(99, 99, 99))))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(jButton1)
                                .addGap(34, 34, 34))
                            .addGroup(javax.swing.GroupLayout.Alignment.LEADING, layout.createSequentialGroup()
                                .addGap(19, 19, 19)
                                .addComponent(jLabel3, javax.swing.GroupLayout.PREFERRED_SIZE, 50, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)))
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(lblmaDinhDanh, javax.swing.GroupLayout.PREFERRED_SIZE, 29, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(txtmaDinhDanh, javax.swing.GroupLayout.PREFERRED_SIZE, 29, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(18, 18, 18)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(lblhoTen, javax.swing.GroupLayout.PREFERRED_SIZE, 29, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(txthoTen, javax.swing.GroupLayout.PREFERRED_SIZE, 28, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(26, 26, 26)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(rbtgioiTinh)
                                .addGap(18, 18, 18)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                                    .addComponent(jLabel5, javax.swing.GroupLayout.PREFERRED_SIZE, 29, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(txtqueQuan, javax.swing.GroupLayout.PREFERRED_SIZE, 29, javax.swing.GroupLayout.PREFERRED_SIZE))
                                .addGap(18, 18, 18)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                                    .addComponent(jLabel6, javax.swing.GroupLayout.PREFERRED_SIZE, 29, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(txtngayDen, javax.swing.GroupLayout.PREFERRED_SIZE, 29, javax.swing.GroupLayout.PREFERRED_SIZE))
                                .addGap(18, 18, 18)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                    .addComponent(txtngayDi, javax.swing.GroupLayout.PREFERRED_SIZE, 29, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(jLabel7, javax.swing.GroupLayout.PREFERRED_SIZE, 29, javax.swing.GroupLayout.PREFERRED_SIZE)))
                            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                .addComponent(rbtnam)
                                .addComponent(rbtnu))))
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(btnthoat, javax.swing.GroupLayout.PREFERRED_SIZE, 32, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(18, 18, 18)
                        .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 338, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 33, Short.MAX_VALUE)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                    .addComponent(rbtdichVu)
                                    .addComponent(rbtcaoCap)
                                    .addComponent(rbtbinhThuong))
                                .addGap(18, 18, 18)
                                .addComponent(rbtloaiPhong)
                                .addGap(45, 45, 45))
                            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                    .addComponent(rbtSingleRoom)
                                    .addComponent(rbtDoubleRoom)
                                    .addComponent(rbtTwinRoom))
                                .addGap(17, 17, 17)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                    .addComponent(rbtTripleRoom)
                                    .addComponent(rbtQuadRoom))
                                .addGap(18, 18, 18)))
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(lblsoLuong)
                            .addComponent(txtsoLuong, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(lbldonGia)
                            .addComponent(txtdonGia, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(btntongTienDichVu, javax.swing.GroupLayout.PREFERRED_SIZE, 40, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(btndocFile, javax.swing.GroupLayout.PREFERRED_SIZE, 40, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(btnluu, javax.swing.GroupLayout.PREFERRED_SIZE, 40, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(btnxoa, javax.swing.GroupLayout.PREFERRED_SIZE, 40, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(18, 18, 18)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(btntongTienThuePhong, javax.swing.GroupLayout.PREFERRED_SIZE, 40, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(btncapNhat, javax.swing.GroupLayout.PREFERRED_SIZE, 40, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(btnsapXep, javax.swing.GroupLayout.PREFERRED_SIZE, 40, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(btnGiam, javax.swing.GroupLayout.PREFERRED_SIZE, 41, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(btnTang, javax.swing.GroupLayout.PREFERRED_SIZE, 41, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addGap(34, 34, 34))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void rbtnamActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_rbtnamActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_rbtnamActionPerformed

    private void rbtnuActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_rbtnuActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_rbtnuActionPerformed

    private void btncapNhatActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btncapNhatActionPerformed
//        // TODO add your handling code here:
    String ma, ht, quequan;
    boolean gt;
    boolean dv;
    String ngayden, ngaydi;
    double sl, dg;
    dv = rbtbinhThuong.isSelected();
       ma=txtmaDinhDanh.getText();
       ht=txthoTen.getText();
       quequan=txtqueQuan.getText();
       ngayden=txtngayDen.getText();
       ngaydi=txtngayDen.getText();
       gt = rbtnam.isSelected();
       sl=Double.parseDouble(txtsoLuong.getText());
       dg=Double.parseDouble(txtdonGia.getText());
       KhachHang y;
       if(rbtgioiTinh.isSelected()){
            boolean loaiDichVu=true;
            if(rbtgioiTinh.isSelected()) loaiDichVu=false;
            y = new DichVu(dv,ma,ht,gt,quequan,ngayden,ngaydi,sl, dg);
        }else{
            String lp ="";
            if(rbtSingleRoom.isSelected()) lp = "SingleRoom";
            if(rbtDoubleRoom.isSelected())lp="DoubleRoom";
            if(rbtTwinRoom.isSelected())lp="TwinRoom";
            if(rbtTripleRoom.isSelected())lp="TripleRoom";
            if(rbtQuadRoom.isSelected())lp="QuadRoom";
            y=new ThuePhong(lp,ma,ht,gt,quequan,ngayden,ngaydi,sl, dg) ;
        }
        if(x.them(y)) loadDuLieu();
        else JOptionPane.showMessageDialog(null,"Da co ma"+ ma+"trong DS cac GD");
    }//GEN-LAST:event_btncapNhatActionPerformed
public void loadDuLieu(){
    ArrayList<KhachHang> b = x.getA();
    while(kb.getRowCount()>0) kb.removeRow(0);
    for(KhachHang y:b)
        if(y instanceof DichVu)
            kb.addRow(new Object[]{y.getMaDinhDanh(),y.getHoTen(),(y.isGioiTinh()?"nam":"nu"),y.getQueQuan(),y.getSoLuong(),y.getNgayDen(),y.getNgayDi()
                ,(((DichVu) y).isLoaiDichVu()?"Binh Thuong":"Cao cap"),"",y.getDonGia(),y.tinhTT()});
        else if(y instanceof ThuePhong){
            kb.addRow(new Object[]{y.getMaDinhDanh(),y.getHoTen(),(y.isGioiTinh()?"nam":"nu"),y.getQueQuan(),y.getSoLuong(),y.getNgayDen(),y.getNgayDi()
           ,"",((ThuePhong) y).getLoaiPhong(),y.getDonGia(),y.tinhTT()});
    }
//    kb.setColumnIdentifiers(new Object []{"Mã Định Danh","Họ Tên","GT","Quê Quán","SL","Ngày Đến","Ngày Đi","Dịch Vụ","Loại Phòng","ĐG","Tính Thành Tiền"});
}
    private void btndocFileActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btndocFileActionPerformed
        // TODO add your handling code here:
        JFileChooser fc = new JFileChooser();
        fc.showOpenDialog(null);
        String st = fc.getSelectedFile().getPath();
        x.docFile(st);
        //a.xuat(st);
        a =x.getA();
        //dua thong tin tu x vao table
        loadDuLieu();
    }//GEN-LAST:event_btndocFileActionPerformed

    private void btnxoaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnxoaActionPerformed
        // TODO add your handling code here:
        int choice = JOptionPane.showConfirmDialog(rootPane, "Bạn có chắc muốn làm mới danh sách ?");
        if (JOptionPane.YES_OPTION == choice) {
            for (int i = 0; i < a.size(); i++) {
                a.remove(a.get(i));
                i--;
            }

            for (int i = 0; i < b.size(); i++) {
                b.remove(b.get(i));
                i--;
            }
        } else {

        }
        loadDuLieu();
        
    }//GEN-LAST:event_btnxoaActionPerformed

    private void btnthoatActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnthoatActionPerformed
        // TODO add your handling code here:
        System.exit(0);
    }//GEN-LAST:event_btnthoatActionPerformed

    private void btntongTienDichVuActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btntongTienDichVuActionPerformed
        // TODO add your handling code here:
        JOptionPane.showMessageDialog(rootPane, "Tổng Tiền Dịch Vụ :"+x.tongHDDichVu());
    }//GEN-LAST:event_btntongTienDichVuActionPerformed

    private void btntongTienThuePhongActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btntongTienThuePhongActionPerformed
        // TODO add your handling code here:
        JOptionPane.showMessageDialog(rootPane, "Tổng Tiền Thuê Phòng :"+x.tongHDKhachHang());
    }//GEN-LAST:event_btntongTienThuePhongActionPerformed

    private void btnluuActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnluuActionPerformed
        // TODO add your handling code here:
        JFileChooser fc = new JFileChooser();
        fc.showSaveDialog(this);
        String tenFile = fc.getSelectedFile().getPath();
        x.ghiFile(tenFile);
        
    }//GEN-LAST:event_btnluuActionPerformed
  int i = 0 ; 
    private void btnsapXepActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnsapXepActionPerformed
        // TODO add your handling code here:
// TODO add your handling code here: 

        btnTang.setVisible(false);
        btnGiam.setVisible(false);
        i++;
//        System.out.println("i : " + i);
        if (i % 2 == 0) {
            btnTang.setVisible(false);
            btnGiam.setVisible(false);
        } else {
            btnTang.setVisible(true);
        btnGiam.setVisible(true);
        }
    }//GEN-LAST:event_btnsapXepActionPerformed

    private void rbtdichVuActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_rbtdichVuActionPerformed
        // TODO add your handling code here:
//        rbtloaiPhong.setVisible(true);
//        rbtDoubleRoom.setVisible(false);
//        rbtSingleRoom.setVisible(false);
//        rbtQuadRoom.setVisible(false);
//        rbtTripleRoom.setVisible(false);
//        rbtTwinRoom.setVisible(false);
//        rbtbinhThuong.setVisible(true);
//        rbtcaoCap.setVisible(true);
    }//GEN-LAST:event_rbtdichVuActionPerformed

    private void rbtloaiPhongActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_rbtloaiPhongActionPerformed
        // TODO add your handling code here:
//        rbtdichVu.setVisible(true);
//        rbtbinhThuong.setVisible(false);
//        rbtcaoCap.setVisible(false);
//        rbtloaiPhong.setVisible(true);
//        rbtDoubleRoom.setVisible(true);
//        rbtSingleRoom.setVisible(true);
//        rbtQuadRoom.setVisible(true);
//        rbtTripleRoom.setVisible(true);
//        rbtTwinRoom.setVisible(true);
        
    }//GEN-LAST:event_rbtloaiPhongActionPerformed

    private void btnGiamActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnGiamActionPerformed
        // TODO add your handling code here:
        Collections.sort(a, (a, b) -> (int) (b.tinhTT() - a.tinhTT()));//lambdatinh
        loadDuLieu();//b-> a giảm
    }//GEN-LAST:event_btnGiamActionPerformed

    private void btnTangActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnTangActionPerformed
        // TODO add your handling code here:
            Collections.sort(a, (a, b) -> (int) (a.tinhTT() - b.tinhTT()));//lambdatinh
        loadDuLieu();//b-> a giảm
    }//GEN-LAST:event_btnTangActionPerformed

    private void rbtgioiTinhActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_rbtgioiTinhActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_rbtgioiTinhActionPerformed

    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jButton1ActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Windows".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(QLKS.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(QLKS.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(QLKS.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(QLKS.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new QLKS().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnGiam;
    private javax.swing.JButton btnTang;
    private javax.swing.JButton btncapNhat;
    private javax.swing.JButton btndocFile;
    private javax.swing.JButton btnluu;
    private javax.swing.JButton btnsapXep;
    private javax.swing.JButton btnthoat;
    private javax.swing.JButton btntongTienDichVu;
    private javax.swing.JButton btntongTienThuePhong;
    private javax.swing.JButton btnxoa;
    private javax.swing.ButtonGroup buttonGroup1;
    private javax.swing.ButtonGroup buttonGroup2;
    private javax.swing.ButtonGroup buttonGroup3;
    private javax.swing.JButton jButton1;
    private javax.swing.JButton jButton6;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JLabel lbldonGia;
    private javax.swing.JLabel lblhoTen;
    private javax.swing.JLabel lblmaDinhDanh;
    private javax.swing.JLabel lblsoLuong;
    private javax.swing.JRadioButton rbtDoubleRoom;
    private javax.swing.JRadioButton rbtQuadRoom;
    private javax.swing.JRadioButton rbtSingleRoom;
    private javax.swing.JRadioButton rbtTripleRoom;
    private javax.swing.JRadioButton rbtTwinRoom;
    private javax.swing.JRadioButton rbtbinhThuong;
    private javax.swing.JRadioButton rbtcaoCap;
    private javax.swing.JButton rbtdichVu;
    private javax.swing.JButton rbtgioiTinh;
    private javax.swing.JButton rbtloaiPhong;
    private javax.swing.JRadioButton rbtnam;
    private javax.swing.JRadioButton rbtnu;
    private javax.swing.JTable tblhienThi;
    private javax.swing.JTextField txtdonGia;
    private javax.swing.JTextField txthoTen;
    private javax.swing.JTextField txtmaDinhDanh;
    private javax.swing.JTextField txtngayDen;
    private javax.swing.JTextField txtngayDi;
    private javax.swing.JTextField txtqueQuan;
    private javax.swing.JTextField txtsoLuong;
    // End of variables declaration//GEN-END:variables
}
