const express = require('express')
const util = require('./util')
const authorize = require('./middleware/authorize')
const system = require('./controllers/SystemController.js')
const authen = require('./controllers/LoginController.js')
const userAccount = require('./controllers/UserAccountController.js')
const jobPosition = require('./controllers/JobPositionController.js')
const department = require('./controllers/DepartmentController.js')
const employeeType = require('./controllers/EmployeeTypeController.js')
const employee = require('./controllers/EmployeeController.js')

module.exports = express.Router()
  .post('/login', authen.login)
  .get('/logout', authen.logout)
  .post('/resetPassword', authen.resetPassword)
  .get('/changePassword/:token', authen.getChangePassword)
  .post('/changePassword/:token', authen.changePassword)
  .get('/user', authen.user)
  .get('/profile', system.profile)
  .post('/updateProfile', system.updateProfile)
  .get('/stack', system.stack)
  .use('/userAccounts', authorize('ADMIN'), express.Router()
    .get('/', userAccount.index)
    .post('/', userAccount.create)
    .get('/create', userAccount.getCreate)
    .get('/:id', userAccount.get)
    .get('/:id/edit', userAccount.edit)
    .put('/:id', userAccount.update)
    .get('/:id/delete', userAccount.getDelete)
    .delete('/:id', userAccount.delete)
  )
  .use('/jobPositions', authorize('ADMIN,USER'), express.Router()
    .get('/', jobPosition.index)
    .post('/', jobPosition.create)
    .get('/create', jobPosition.getCreate)
    .get('/:jobPositionId', jobPosition.get)
    .get('/:jobPositionId/edit', jobPosition.edit)
    .put('/:jobPositionId', jobPosition.update)
    .get('/:jobPositionId/delete', jobPosition.getDelete)
    .delete('/:jobPositionId', jobPosition.delete)
  )
  .use('/departments', authorize('ADMIN,USER'), express.Router()
    .get('/', department.index)
    .post('/', department.create)
    .get('/create', department.getCreate)
    .get('/:departmentId', department.get)
    .get('/:departmentId/edit', department.edit)
    .put('/:departmentId', department.update)
    .get('/:departmentId/delete', department.getDelete)
    .delete('/:departmentId', department.delete)
  )
  .use('/employeeTypes', authorize('ADMIN,USER'), express.Router()
    .get('/', employeeType.index)
    .post('/', employeeType.create)
    .get('/create', employeeType.getCreate)
    .get('/:employeeTypeId', employeeType.get)
    .get('/:employeeTypeId/edit', employeeType.edit)
    .put('/:employeeTypeId', employeeType.update)
    .get('/:employeeTypeId/delete', employeeType.getDelete)
    .delete('/:employeeTypeId', employeeType.delete)
  )
  .use('/employees', authorize('ADMIN,USER'), express.Router()
    .get('/', employee.index)
    .post('/', employee.create)
    .get('/create', employee.getCreate)
    .get('/:employeeId/:departmentId/:employeeTypeId/:branchId/:jobPositionId', employee.get)
    .get('/:employeeId/:departmentId/:employeeTypeId/:branchId/:jobPositionId/edit', employee.edit)
    .put('/:employeeId/:departmentId/:employeeTypeId/:branchId/:jobPositionId', employee.update)
    .get('/:employeeId/:departmentId/:employeeTypeId/:branchId/:jobPositionId/delete', employee.getDelete)
    .delete('/:employeeId/:departmentId/:employeeTypeId/:branchId/:jobPositionId', employee.delete)
  )
