/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */

import java.awt.JobAttributes;
import java.awt.event.ActionListener;
import java.util.ArrayList;
import java.util.Collection;
import java.util.Collections;
import java.util.Comparator;
import javax.management.modelmbean.ModelMBean;
import javax.swing.JFileChooser;
import javax.swing.JFrame;
import javax.swing.JOptionPane;
import javax.swing.JTable;
import javax.swing.JTextArea;
import javax.swing.table.DefaultTableModel;

/**
 *
 * @author ADMIN
 */
public class Quan_Ly_Phuong_Tien extends javax.swing.JFrame {

    /**
     * Creates new form Quan_Ly_Nhan_Vien
     */
    ArrayList<PhuongTien> a = new ArrayList<>();
    ArrayList<PhuongTien> b = new ArrayList<>();
    ArrayList<PhuongTien> c = new ArrayList<>();
    DefaultTableModel model; //tao doi tuong 
    QLPTGT x = new QLPTGT();

    public Quan_Ly_Phuong_Tien() {
        initComponents();
        model = new DefaultTableModel();//ok
        this.setLocationRelativeTo(null);//cho no o giua
        this.setDefaultCloseOperation(JFrame.EXIT_ON_CLOSE);//dong dc dau x 
        this.setResizable(false);
        model.setColumnIdentifiers(new Object[]{
            "ID", "Hang SX", "NAM SX", "GIA BAN", "MAU XE", "SO CHO NGOI", "KIEU DONG CO", "CONG SUAT",
            "TRONG TAI"
        });
        tableHienThi.setModel(model);
        txtCongSuat.setVisible(false);
        txtLTrongTai.setVisible(false);
        jLabel14.setVisible(false);
        jLabel15.setVisible(false);

    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        buttonGroup1 = new javax.swing.ButtonGroup();
        buttonGroup2 = new javax.swing.ButtonGroup();
        buttonGroup3 = new javax.swing.ButtonGroup();
        jLabel8 = new javax.swing.JLabel();
        jScrollPane1 = new javax.swing.JScrollPane();
        tableHienThi = new javax.swing.JTable();
        btThemMoi = new javax.swing.JButton();
        btNhapLai = new javax.swing.JButton();
        btDocFile = new javax.swing.JButton();
        btThoat = new javax.swing.JButton();
        btTimKiem = new javax.swing.JButton();
        btLuuFile = new javax.swing.JButton();
        jLabel9 = new javax.swing.JLabel();
        btClear = new javax.swing.JButton();
        jScrollPane2 = new javax.swing.JScrollPane();
        jtThongBao = new javax.swing.JTextArea();
        jLabel1 = new javax.swing.JLabel();
        jLabel11 = new javax.swing.JLabel();
        txtHangSanXuat = new javax.swing.JTextField();
        jLabel7 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        txtGiaBan = new javax.swing.JTextField();
        jLabel5 = new javax.swing.JLabel();
        jLabel10 = new javax.swing.JLabel();
        cbbLoaiXe = new javax.swing.JComboBox<>();
        txtMauXe = new javax.swing.JTextField();
        txtNamSanXuat = new javax.swing.JTextField();
        txtID = new javax.swing.JTextField();
        jLabel2 = new javax.swing.JLabel();
        jLabel6 = new javax.swing.JLabel();
        btnOTO = new javax.swing.JButton();
        jLabel12 = new javax.swing.JLabel();
        txtSoCho = new javax.swing.JTextField();
        jLabel13 = new javax.swing.JLabel();
        txtLDC = new javax.swing.JTextField();
        btnXeMay = new javax.swing.JButton();
        jLabel14 = new javax.swing.JLabel();
        txtCongSuat = new javax.swing.JTextField();
        btThemMoi3 = new javax.swing.JButton();
        jLabel15 = new javax.swing.JLabel();
        txtLTrongTai = new javax.swing.JTextField();
        jLabel4 = new javax.swing.JLabel();
        timKiemHSX = new javax.swing.JTextField();
        jLabel16 = new javax.swing.JLabel();
        timkiemMauXe = new javax.swing.JTextField();
        jLabel17 = new javax.swing.JLabel();
        removeID = new javax.swing.JTextField();
        btnXoa = new javax.swing.JButton();
        btnLamMoi = new javax.swing.JButton();
        jLabel18 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setTitle("Quản lý nhân viên");

        jLabel8.setFont(new java.awt.Font("Segoe UI", 1, 24)); // NOI18N
        jLabel8.setText("QUẢN LÝ PHƯƠNG TIỆN");

        tableHienThi.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {},
                {},
                {},
                {}
            },
            new String [] {

            }
        ));
        jScrollPane1.setViewportView(tableHienThi);

        btThemMoi.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        btThemMoi.setIcon(new javax.swing.ImageIcon("D:\\Project_java_hoan_chinh\\img\\Button-Add-icon.png")); // NOI18N
        btThemMoi.setText("THÊM MỚI");
        buttonGroup3.add(btThemMoi);
        btThemMoi.addFocusListener(new java.awt.event.FocusAdapter() {
            public void focusLost(java.awt.event.FocusEvent evt) {
                btThemMoiFocusLost(evt);
            }
        });
        btThemMoi.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btThemMoiActionPerformed(evt);
            }
        });

        btNhapLai.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        btNhapLai.setText("NHẬP LẠI");
        buttonGroup3.add(btNhapLai);
        btNhapLai.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btNhapLaiActionPerformed(evt);
            }
        });

        btDocFile.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        btDocFile.setText("ĐỌC FILE");
        buttonGroup3.add(btDocFile);
        btDocFile.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btDocFileActionPerformed(evt);
            }
        });

        btThoat.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        btThoat.setText("THOÁT");
        buttonGroup3.add(btThoat);
        btThoat.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btThoatActionPerformed(evt);
            }
        });

        btTimKiem.setBackground(new java.awt.Color(51, 51, 51));
        btTimKiem.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        btTimKiem.setForeground(new java.awt.Color(255, 255, 255));
        btTimKiem.setText("TÌM KIẾM ");
        btTimKiem.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btTimKiemActionPerformed(evt);
            }
        });

        btLuuFile.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        btLuuFile.setText("LƯU FILE");
        buttonGroup3.add(btLuuFile);
        btLuuFile.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btLuuFileActionPerformed(evt);
            }
        });

        jLabel9.setFont(new java.awt.Font("Segoe UI", 1, 18)); // NOI18N
        jLabel9.setForeground(new java.awt.Color(255, 0, 0));
        jLabel9.setText("BẢNG THÔNG BÁO");

        btClear.setBackground(new java.awt.Color(0, 0, 0));
        btClear.setFont(new java.awt.Font("Segoe UI", 0, 18)); // NOI18N
        btClear.setForeground(new java.awt.Color(255, 255, 255));
        btClear.setText("Clear");
        btClear.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btClearActionPerformed(evt);
            }
        });

        jtThongBao.setColumns(20);
        jtThongBao.setRows(5);
        jScrollPane2.setViewportView(jtThongBao);

        jLabel1.setFont(new java.awt.Font("Segoe UI", 2, 14)); // NOI18N
        jLabel1.setForeground(new java.awt.Color(255, 51, 51));
        jLabel1.setText("Đây là bản quyền của : Trương Nguyễn Khải");

        txtHangSanXuat.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        txtHangSanXuat.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtHangSanXuatActionPerformed(evt);
            }
        });

        jLabel7.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        jLabel7.setText("ID:");

        jLabel3.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        jLabel3.setText("NĂM SẢN XUẤT:");

        txtGiaBan.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N

        jLabel5.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        jLabel5.setText("LOẠI XE:");

        jLabel10.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        jLabel10.setText("MÀU XE:");

        cbbLoaiXe.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Xe Oto", "Xe May", "Xe Tai", " " }));
        cbbLoaiXe.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                cbbLoaiXeActionPerformed(evt);
            }
        });

        txtMauXe.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        txtMauXe.addFocusListener(new java.awt.event.FocusAdapter() {
            public void focusLost(java.awt.event.FocusEvent evt) {
                txtMauXeFocusLost(evt);
            }
        });
        txtMauXe.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtMauXeActionPerformed(evt);
            }
        });

        txtNamSanXuat.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N

        txtID.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N

        jLabel2.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        jLabel2.setText("HÃNG SẢN XUẤT:");

        jLabel6.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        jLabel6.setText("GIÁ BÁN:");

        btnOTO.setFont(new java.awt.Font("Segoe UI", 1, 16)); // NOI18N
        btnOTO.setForeground(new java.awt.Color(255, 51, 51));
        btnOTO.setText("Ô TÔ ");
        buttonGroup3.add(btnOTO);
        btnOTO.addFocusListener(new java.awt.event.FocusAdapter() {
            public void focusLost(java.awt.event.FocusEvent evt) {
                btnOTOFocusLost(evt);
            }
        });
        btnOTO.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnOTOActionPerformed(evt);
            }
        });

        jLabel12.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        jLabel12.setText("SỐ CHỖ: ");

        txtSoCho.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        txtSoCho.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtSoChoActionPerformed(evt);
            }
        });

        jLabel13.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        jLabel13.setText("LDC:");

        txtLDC.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        txtLDC.addFocusListener(new java.awt.event.FocusAdapter() {
            public void focusLost(java.awt.event.FocusEvent evt) {
                txtLDCFocusLost(evt);
            }
        });
        txtLDC.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtLDCActionPerformed(evt);
            }
        });

        btnXeMay.setFont(new java.awt.Font("Segoe UI", 1, 16)); // NOI18N
        btnXeMay.setForeground(new java.awt.Color(255, 51, 51));
        btnXeMay.setText("XE MÁY");
        buttonGroup3.add(btnXeMay);
        btnXeMay.addFocusListener(new java.awt.event.FocusAdapter() {
            public void focusLost(java.awt.event.FocusEvent evt) {
                btnXeMayFocusLost(evt);
            }
        });
        btnXeMay.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnXeMayActionPerformed(evt);
            }
        });

        jLabel14.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        jLabel14.setText("CÔNG SUẤT:");

        txtCongSuat.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        txtCongSuat.addFocusListener(new java.awt.event.FocusAdapter() {
            public void focusLost(java.awt.event.FocusEvent evt) {
                txtCongSuatFocusLost(evt);
            }
        });
        txtCongSuat.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtCongSuatActionPerformed(evt);
            }
        });

        btThemMoi3.setFont(new java.awt.Font("Segoe UI", 1, 16)); // NOI18N
        btThemMoi3.setForeground(new java.awt.Color(255, 51, 51));
        btThemMoi3.setText("XE TẢI");
        buttonGroup3.add(btThemMoi3);
        btThemMoi3.addFocusListener(new java.awt.event.FocusAdapter() {
            public void focusLost(java.awt.event.FocusEvent evt) {
                btThemMoi3FocusLost(evt);
            }
        });
        btThemMoi3.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btThemMoi3ActionPerformed(evt);
            }
        });

        jLabel15.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        jLabel15.setText("TRỌNG TẢI:");

        txtLTrongTai.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        txtLTrongTai.addFocusListener(new java.awt.event.FocusAdapter() {
            public void focusLost(java.awt.event.FocusEvent evt) {
                txtLTrongTaiFocusLost(evt);
            }
        });
        txtLTrongTai.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtLTrongTaiActionPerformed(evt);
            }
        });

        jLabel4.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        jLabel4.setText("HÃNG SẢN XUẤT:");

        timKiemHSX.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        timKiemHSX.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                timKiemHSXActionPerformed(evt);
            }
        });

        jLabel16.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        jLabel16.setText("MÀU XE:");

        timkiemMauXe.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        timkiemMauXe.addFocusListener(new java.awt.event.FocusAdapter() {
            public void focusLost(java.awt.event.FocusEvent evt) {
                timkiemMauXeFocusLost(evt);
            }
        });
        timkiemMauXe.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                timkiemMauXeActionPerformed(evt);
            }
        });

        jLabel17.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        jLabel17.setText("Nhap ID can xoa:");

        removeID.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N

        btnXoa.setBackground(new java.awt.Color(51, 51, 51));
        btnXoa.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        btnXoa.setForeground(new java.awt.Color(255, 255, 255));
        btnXoa.setText("XÓA");
        btnXoa.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnXoaActionPerformed(evt);
            }
        });

        btnLamMoi.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        btnLamMoi.setText("LÀM MỚI ");
        buttonGroup3.add(btnLamMoi);
        btnLamMoi.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnLamMoiActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(24, 24, 24)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                        .addGap(0, 0, Short.MAX_VALUE)
                        .addComponent(jLabel9)
                        .addGap(54, 54, 54)
                        .addComponent(btClear))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                                    .addGroup(layout.createSequentialGroup()
                                        .addComponent(jLabel7)
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                        .addComponent(txtID, javax.swing.GroupLayout.PREFERRED_SIZE, 170, javax.swing.GroupLayout.PREFERRED_SIZE))
                                    .addGroup(layout.createSequentialGroup()
                                        .addComponent(jLabel5)
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                        .addComponent(cbbLoaiXe, javax.swing.GroupLayout.PREFERRED_SIZE, 172, javax.swing.GroupLayout.PREFERRED_SIZE))
                                    .addGroup(layout.createSequentialGroup()
                                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                                .addComponent(jLabel6)
                                                .addComponent(jLabel10))
                                            .addComponent(jLabel3, javax.swing.GroupLayout.Alignment.TRAILING))
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                                            .addComponent(txtGiaBan, javax.swing.GroupLayout.Alignment.LEADING)
                                            .addComponent(txtNamSanXuat)
                                            .addComponent(txtMauXe, javax.swing.GroupLayout.PREFERRED_SIZE, 172, javax.swing.GroupLayout.PREFERRED_SIZE)))
                                    .addGroup(layout.createSequentialGroup()
                                        .addComponent(jLabel2)
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                        .addComponent(txtHangSanXuat, javax.swing.GroupLayout.PREFERRED_SIZE, 172, javax.swing.GroupLayout.PREFERRED_SIZE)))
                                .addGap(157, 157, 157))
                            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                                .addComponent(btnOTO, javax.swing.GroupLayout.PREFERRED_SIZE, 99, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(0, 0, Short.MAX_VALUE)))
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(btTimKiem, javax.swing.GroupLayout.PREFERRED_SIZE, 130, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(jLabel4)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(timKiemHSX, javax.swing.GroupLayout.PREFERRED_SIZE, 172, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(jLabel16)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(timkiemMauXe, javax.swing.GroupLayout.PREFERRED_SIZE, 172, javax.swing.GroupLayout.PREFERRED_SIZE)))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jScrollPane2, javax.swing.GroupLayout.PREFERRED_SIZE, 410, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addComponent(btnXeMay, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(btThemMoi3, javax.swing.GroupLayout.PREFERRED_SIZE, 101, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(jLabel14)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(txtCongSuat, javax.swing.GroupLayout.PREFERRED_SIZE, 168, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 160, Short.MAX_VALUE)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addGroup(layout.createSequentialGroup()
                                        .addComponent(btnXoa, javax.swing.GroupLayout.PREFERRED_SIZE, 130, javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                        .addComponent(jLabel17)
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                        .addComponent(removeID, javax.swing.GroupLayout.PREFERRED_SIZE, 170, javax.swing.GroupLayout.PREFERRED_SIZE))
                                    .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 788, javax.swing.GroupLayout.PREFERRED_SIZE)))
                            .addGroup(layout.createSequentialGroup()
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addGroup(layout.createSequentialGroup()
                                        .addGap(89, 89, 89)
                                        .addComponent(jLabel8, javax.swing.GroupLayout.PREFERRED_SIZE, 332, javax.swing.GroupLayout.PREFERRED_SIZE))
                                    .addGroup(layout.createSequentialGroup()
                                        .addComponent(jLabel15)
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                        .addComponent(txtLTrongTai, javax.swing.GroupLayout.PREFERRED_SIZE, 172, javax.swing.GroupLayout.PREFERRED_SIZE))
                                    .addGroup(layout.createSequentialGroup()
                                        .addGap(21, 21, 21)
                                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                                                    .addComponent(jLabel13)
                                                    .addComponent(jLabel12))
                                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                                                    .addComponent(txtSoCho, javax.swing.GroupLayout.Alignment.LEADING)
                                                    .addComponent(txtLDC, javax.swing.GroupLayout.PREFERRED_SIZE, 172, javax.swing.GroupLayout.PREFERRED_SIZE)))
                                            .addComponent(jLabel11)))
                                    .addGroup(layout.createSequentialGroup()
                                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                            .addComponent(btThemMoi, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                            .addComponent(btDocFile, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                                        .addGap(32, 32, 32)
                                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                            .addComponent(btNhapLai)
                                            .addComponent(btLuuFile, javax.swing.GroupLayout.PREFERRED_SIZE, 126, javax.swing.GroupLayout.PREFERRED_SIZE))
                                        .addGap(30, 30, 30)
                                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                            .addComponent(btnLamMoi, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                            .addComponent(btThoat, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))))
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                .addComponent(jLabel18, javax.swing.GroupLayout.PREFERRED_SIZE, 71, javax.swing.GroupLayout.PREFERRED_SIZE)))))
                .addContainerGap())
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addGap(0, 0, Short.MAX_VALUE)
                .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 295, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(45, 45, 45))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel8, javax.swing.GroupLayout.PREFERRED_SIZE, 53, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel9, javax.swing.GroupLayout.PREFERRED_SIZE, 35, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(btClear))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 10, Short.MAX_VALUE)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                        .addGap(125, 125, 125)
                        .addComponent(jLabel11, javax.swing.GroupLayout.PREFERRED_SIZE, 107, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(layout.createSequentialGroup()
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                    .addComponent(jLabel7, javax.swing.GroupLayout.PREFERRED_SIZE, 35, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(txtID, javax.swing.GroupLayout.PREFERRED_SIZE, 35, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(btTimKiem, javax.swing.GroupLayout.PREFERRED_SIZE, 31, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(jLabel4, javax.swing.GroupLayout.PREFERRED_SIZE, 35, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(timKiemHSX, javax.swing.GroupLayout.PREFERRED_SIZE, 35, javax.swing.GroupLayout.PREFERRED_SIZE))
                                .addGap(17, 17, 17)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                        .addComponent(jLabel5, javax.swing.GroupLayout.PREFERRED_SIZE, 35, javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addComponent(cbbLoaiXe, javax.swing.GroupLayout.PREFERRED_SIZE, 35, javax.swing.GroupLayout.PREFERRED_SIZE))
                                    .addComponent(timkiemMauXe, javax.swing.GroupLayout.PREFERRED_SIZE, 35, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(jLabel16, javax.swing.GroupLayout.PREFERRED_SIZE, 35, javax.swing.GroupLayout.PREFERRED_SIZE))
                                .addGap(24, 24, 24)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                    .addComponent(jLabel2, javax.swing.GroupLayout.PREFERRED_SIZE, 35, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(txtHangSanXuat, javax.swing.GroupLayout.PREFERRED_SIZE, 35, javax.swing.GroupLayout.PREFERRED_SIZE))
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                    .addComponent(jLabel3, javax.swing.GroupLayout.PREFERRED_SIZE, 35, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(txtNamSanXuat, javax.swing.GroupLayout.PREFERRED_SIZE, 35, javax.swing.GroupLayout.PREFERRED_SIZE))
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(txtGiaBan, javax.swing.GroupLayout.PREFERRED_SIZE, 35, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(jLabel6, javax.swing.GroupLayout.PREFERRED_SIZE, 35, javax.swing.GroupLayout.PREFERRED_SIZE))
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(txtMauXe, javax.swing.GroupLayout.PREFERRED_SIZE, 35, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(jLabel10, javax.swing.GroupLayout.PREFERRED_SIZE, 35, javax.swing.GroupLayout.PREFERRED_SIZE))
                                .addGap(25, 25, 25)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(btnOTO)
                                    .addGroup(layout.createSequentialGroup()
                                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                            .addComponent(txtSoCho, javax.swing.GroupLayout.PREFERRED_SIZE, 35, javax.swing.GroupLayout.PREFERRED_SIZE)
                                            .addComponent(jLabel12, javax.swing.GroupLayout.PREFERRED_SIZE, 35, javax.swing.GroupLayout.PREFERRED_SIZE))
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                            .addComponent(txtLDC, javax.swing.GroupLayout.PREFERRED_SIZE, 35, javax.swing.GroupLayout.PREFERRED_SIZE)
                                            .addComponent(jLabel13, javax.swing.GroupLayout.PREFERRED_SIZE, 35, javax.swing.GroupLayout.PREFERRED_SIZE))))
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                    .addComponent(txtCongSuat, javax.swing.GroupLayout.PREFERRED_SIZE, 35, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(jLabel14, javax.swing.GroupLayout.PREFERRED_SIZE, 35, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(btnXeMay)))
                            .addGroup(layout.createSequentialGroup()
                                .addGap(1, 1, 1)
                                .addComponent(jScrollPane2, javax.swing.GroupLayout.PREFERRED_SIZE, 112, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 293, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 8, Short.MAX_VALUE)))
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel17, javax.swing.GroupLayout.PREFERRED_SIZE, 35, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(removeID, javax.swing.GroupLayout.PREFERRED_SIZE, 35, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(btnXoa, javax.swing.GroupLayout.PREFERRED_SIZE, 31, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(18, 18, 18)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(btThemMoi3)
                            .addComponent(jLabel15, javax.swing.GroupLayout.PREFERRED_SIZE, 35, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(txtLTrongTai, javax.swing.GroupLayout.PREFERRED_SIZE, 35, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(35, 35, 35)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                            .addComponent(btThemMoi, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(btNhapLai, javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(btThoat, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(layout.createSequentialGroup()
                                .addGap(18, 18, 18)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                    .addComponent(btLuuFile, javax.swing.GroupLayout.PREFERRED_SIZE, 31, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(btDocFile, javax.swing.GroupLayout.PREFERRED_SIZE, 31, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(btnLamMoi, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)))
                            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 8, Short.MAX_VALUE)
                                .addComponent(jLabel18, javax.swing.GroupLayout.PREFERRED_SIZE, 60, javax.swing.GroupLayout.PREFERRED_SIZE)))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jLabel1)))
                .addContainerGap())
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents


    private void btThemMoiActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btThemMoiActionPerformed
        String id, hangSanXuat = "";
        double namSanXuat, giaBan;
        String id1 = txtID.getText();
        String hang1 = txtHangSanXuat.getText();
        String namSanXuat1 = txtNamSanXuat.getText();
        String giaBan1 = txtGiaBan.getText();
        String mauXe1 = txtMauXe.getText();
        String scn1 = txtSoCho.getText();
        String ldc1 = txtLDC.getText();
        String cs1 = txtCongSuat.getText();
        String tt1 = txtLTrongTai.getText();
        String mauXe;
        id = txtID.getText();
        int index = cbbLoaiXe.getSelectedIndex();
        String lx = "";
        if (index >= 0) {
            lx = cbbLoaiXe.getItemAt(index);
        }
        String batKyTu1 = lx.substring(0, 4);
//        String batKyTu = id.substring(0, 1);
        if (id1.isEmpty()) {
//              JOptionPane.showMessageDialog(rootPane, "Mã không được để trống", "Thông báo", HEIGHT);
            JOptionPane.showMessageDialog(null, "Mã không được bỏ trống", "Thông báo", JOptionPane.WARNING_MESSAGE);
        } else if (hang1.isEmpty()) {
            JOptionPane.showMessageDialog(null, "Hãng sản xuất không được bỏ trống", "Thông báo", JOptionPane.WARNING_MESSAGE);
        } else if (namSanXuat1.isEmpty()) {
            JOptionPane.showMessageDialog(null, "Năm sản xuất không được bỏ trống", "Thông báo", JOptionPane.WARNING_MESSAGE);
        } else if (giaBan1.isEmpty()) {
            JOptionPane.showMessageDialog(null, "Giá bán không được bỏ trống", "Thông báo", JOptionPane.WARNING_MESSAGE);
        } else if (mauXe1.isEmpty()) {
            JOptionPane.showMessageDialog(null, "Màu xe không được bỏ trống", "Thông báo", JOptionPane.WARNING_MESSAGE);
        } else if (batKyTu1.trim().equalsIgnoreCase("Xe o".trim())) {
            if (scn1.isEmpty()) {
                JOptionPane.showMessageDialog(null, "Số chỗ ngồi không được bỏ trống", "Thông báo", JOptionPane.WARNING_MESSAGE);
            } else if (ldc1.isEmpty()) {
                JOptionPane.showMessageDialog(null, "Loại động cơ không được bỏ trống", "Thông báo", JOptionPane.WARNING_MESSAGE);
            } else {
                double soChoNgoi;
                String kieuDongCo = "";
                hangSanXuat = txtHangSanXuat.getText();
                namSanXuat = Double.parseDouble(txtNamSanXuat.getText());
                giaBan = Double.parseDouble(txtGiaBan.getText());
                mauXe = txtMauXe.getText();
                soChoNgoi = Double.parseDouble(txtSoCho.getText());
                kieuDongCo = txtLDC.getText();
                a.add(new Oto(soChoNgoi, kieuDongCo, id, hangSanXuat, mauXe, namSanXuat, giaBan));
            }
        } else if (batKyTu1.trim().equalsIgnoreCase("Xe m".trim())) {
            if (cs1.isEmpty()) {
                JOptionPane.showMessageDialog(null, "Công suất không được bỏ trống", "Thông báo", JOptionPane.WARNING_MESSAGE);
            } else {
                String congSuat = "";
                hangSanXuat = txtHangSanXuat.getText();
                namSanXuat = Double.parseDouble(txtNamSanXuat.getText());
                giaBan = Double.parseDouble(txtGiaBan.getText());
                mauXe = txtMauXe.getText();
                congSuat = txtCongSuat.getText();
                a.add(new XeMay(congSuat, id, hangSanXuat, mauXe, namSanXuat, giaBan));
            }
        } else if (batKyTu1.trim().equalsIgnoreCase("Xe t".trim())) {
            if (tt1.isEmpty()) {
                JOptionPane.showMessageDialog(null, "Trọng tải không được bỏ trống", "Thông báo", JOptionPane.WARNING_MESSAGE);
            } else {
                String trongTai;
                hangSanXuat = txtHangSanXuat.getText();
                namSanXuat = Double.parseDouble(txtNamSanXuat.getText());
                giaBan = Double.parseDouble(txtGiaBan.getText());
                mauXe = txtMauXe.getText();
                trongTai = txtLTrongTai.getText();
                a.add(new XeTai(trongTai, id, hangSanXuat, mauXe, namSanXuat, giaBan));
            }

        }

        showResult();
    }//GEN-LAST:event_btThemMoiActionPerformed

    private void btNhapLaiActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btNhapLaiActionPerformed
        txtID.setText("");
        txtCongSuat.setText("");
        txtGiaBan.setText("");
        txtHangSanXuat.setText("");
        txtLDC.setText("");
        txtLTrongTai.setText("");
        txtMauXe.setText("");
        txtNamSanXuat.setText("");
        txtSoCho.setText("");

    }//GEN-LAST:event_btNhapLaiActionPerformed

    private void btDocFileActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btDocFileActionPerformed
        JFileChooser fc = new JFileChooser("D://");
        fc.showOpenDialog(this);
        String tenFile = fc.getSelectedFile().getPath();
        x.docFile(tenFile);//tenfile
        a = x.getA();
        JOptionPane.showMessageDialog(rootPane, "Mở file thành công");
        showResult();
    }//GEN-LAST:event_btDocFileActionPerformed

    private void btThoatActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btThoatActionPerformed
        System.exit(0);//đóng

    }//GEN-LAST:event_btThoatActionPerformed

    private void btTimKiemActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btTimKiemActionPerformed
        int dem = 1;
        String tkHang = timKiemHSX.getText();
        String tkMau = timkiemMauXe.getText();
        if (tkHang.isEmpty()) {
            JOptionPane.showMessageDialog(null, "Hãng sản xuất không được để trống", "Thông báo", JOptionPane.WARNING_MESSAGE);
        }

        if (tkMau.isEmpty()) {
            JOptionPane.showMessageDialog(null, "Màu xe không được bỏ trống", "Thông báo", JOptionPane.WARNING_MESSAGE);
        }
        for (PhuongTien x : a) {
            if (x.getHangSanXuat().trim().equalsIgnoreCase(tkHang.trim())
                    && x.getMauXe().trim().equalsIgnoreCase(tkMau.trim())) {
                JOptionPane.showMessageDialog(rootPane, "" + x);
            }
        }

        showResult();
    }//GEN-LAST:event_btTimKiemActionPerformed

    private void btLuuFileActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btLuuFileActionPerformed
        JFileChooser fc = new JFileChooser("D://");
        fc.showSaveDialog(this);
        String tenFile = fc.getSelectedFile().getPath();
        x.ghiFile(tenFile);

    }//GEN-LAST:event_btLuuFileActionPerformed

    private void btClearActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btClearActionPerformed
        jtThongBao.setText("");
    }//GEN-LAST:event_btClearActionPerformed

    private void btThemMoiFocusLost(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_btThemMoiFocusLost

    }//GEN-LAST:event_btThemMoiFocusLost

    private void txtHangSanXuatActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtHangSanXuatActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtHangSanXuatActionPerformed

    private void txtMauXeFocusLost(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_txtMauXeFocusLost

    }//GEN-LAST:event_txtMauXeFocusLost

    private void txtMauXeActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtMauXeActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtMauXeActionPerformed

    private void cbbLoaiXeActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_cbbLoaiXeActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_cbbLoaiXeActionPerformed

    private void btnOTOFocusLost(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_btnOTOFocusLost
        // TODO add your handling code here:
    }//GEN-LAST:event_btnOTOFocusLost

    private void btnOTOActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnOTOActionPerformed
        // TODO add your handling code here:
        jLabel12.setVisible(true);
        txtSoCho.setVisible(true);
        jLabel13.setVisible(true);
        txtLDC.setVisible(true);
        txtCongSuat.setVisible(false);
        jLabel14.setVisible(false);
        jLabel15.setVisible(false);
        txtLTrongTai.setVisible(false);
    }//GEN-LAST:event_btnOTOActionPerformed

    private void txtLDCFocusLost(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_txtLDCFocusLost
        // TODO add your handling code here:
    }//GEN-LAST:event_txtLDCFocusLost

    private void txtLDCActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtLDCActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtLDCActionPerformed

    private void btnXeMayActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnXeMayActionPerformed
        // TODO add your handling code here:
        jLabel14.setVisible(true);
        txtCongSuat.setVisible(true);
        txtSoCho.setVisible(false);
        txtLDC.setVisible(false);
        jLabel12.setVisible(false);
        jLabel13.setVisible(false);
        jLabel15.setVisible(false);
        txtLTrongTai.setVisible(false);


    }//GEN-LAST:event_btnXeMayActionPerformed

    private void btnXeMayFocusLost(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_btnXeMayFocusLost
        // TODO add your handling code here:
    }//GEN-LAST:event_btnXeMayFocusLost

    private void btThemMoi3FocusLost(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_btThemMoi3FocusLost
        // TODO add your handling code here:
    }//GEN-LAST:event_btThemMoi3FocusLost

    private void btThemMoi3ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btThemMoi3ActionPerformed
        // TODO add your handling code here:
        jLabel14.setVisible(false);
        txtCongSuat.setVisible(false);
        jLabel12.setVisible(false);
        jLabel13.setVisible(false);
        txtSoCho.setVisible(false);
        txtLDC.setVisible(false);
        jLabel15.setVisible(true);
        txtLTrongTai.setVisible(true);
    }//GEN-LAST:event_btThemMoi3ActionPerformed

    private void txtLTrongTaiFocusLost(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_txtLTrongTaiFocusLost
        // TODO add your handling code here:
    }//GEN-LAST:event_txtLTrongTaiFocusLost

    private void txtLTrongTaiActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtLTrongTaiActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtLTrongTaiActionPerformed

    private void txtSoChoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtSoChoActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtSoChoActionPerformed

    private void txtCongSuatActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtCongSuatActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtCongSuatActionPerformed

    private void txtCongSuatFocusLost(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_txtCongSuatFocusLost
        // TODO add your handling code here:
    }//GEN-LAST:event_txtCongSuatFocusLost

    private void timKiemHSXActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_timKiemHSXActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_timKiemHSXActionPerformed

    private void timkiemMauXeFocusLost(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_timkiemMauXeFocusLost
        // TODO add your handling code here:
    }//GEN-LAST:event_timkiemMauXeFocusLost

    private void timkiemMauXeActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_timkiemMauXeActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_timkiemMauXeActionPerformed

    private void btnXoaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnXoaActionPerformed
        // TODO add your handling code here:
        String maXoa = removeID.getText();
        if (maXoa.isEmpty()) {
            JOptionPane.showMessageDialog(null, "Mã cần xóa không được bỏ trống", "Thông báo", JOptionPane.WARNING_MESSAGE);
        }
        for (int i = 0; i < a.size(); i++) {
            if (a.get(i).getId().trim().equalsIgnoreCase(maXoa.trim())) {
                a.remove(a.get(i));
                i--;
            }
        }

        showResult();

//         int removeIndex = tableHienThi.getSelectedRow();//click len bang thi lay duoc chi so 
//        if (removeIndex == -1) {
//            JOptionPane.showMessageDialog(rootPane, "Hãy chọn một dòng rồi xóa !");
//        } else {
//            int choice = JOptionPane.showConfirmDialog(rootPane, "Bạn có chắc chắn muốn xóa ? ");
//            if (JOptionPane.YES_OPTION == choice) {
//                a.remove(removeIndex);
//            } else {
//
//            }
//
//        }
//
//        showResult();
    }//GEN-LAST:event_btnXoaActionPerformed

    private void btnLamMoiActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnLamMoiActionPerformed
        // TODO add your handling code here:

        int choice = JOptionPane.showConfirmDialog(rootPane, "Bạn có chắc chắn muốn làm mới danh sách ? ");
        if (JOptionPane.YES_OPTION == choice) {
            for (int i = 0; i < a.size(); i++) {
                a.remove(a.get(i));
                i--;
            }
        }
        showResult();
    }//GEN-LAST:event_btnLamMoiActionPerformed

    public void showResult() {//lay du lieu ( tra về dữ liệu ) // in ra du lieu tren bang
        while (model.getRowCount() > 0) {
            model.removeRow(0);
        }
        for (PhuongTien y : a) {
            if (y instanceof Oto) {
                model.addRow(new Object[]{
                    y.getId(), y.getHangSanXuat(), (int) y.getNamSanXuat(), y.getGiaBan(), y.getMauXe(), (int) ((Oto) y).getSoChoNgoi(),
                    ((Oto) y).getKieuDongCo(), "", ""
                });
            } else if (y instanceof XeMay) {
                model.addRow(new Object[]{
                    y.getId(), y.getHangSanXuat(), (int) y.getNamSanXuat(), y.getGiaBan(), y.getMauXe(), "", "", ((XeMay) y).getCongSuat(), ""
                });
            } else if (y instanceof XeTai) {
                model.addRow(new Object[]{
                    y.getId(), y.getHangSanXuat(), (int) y.getNamSanXuat(), y.getGiaBan(), y.getMauXe(), "", "", "", ((XeTai) y).getTrongTai()
                });
            }
        }
    }

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Quan_Ly_Phuong_Tien.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Quan_Ly_Phuong_Tien.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Quan_Ly_Phuong_Tien.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Quan_Ly_Phuong_Tien.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new Quan_Ly_Phuong_Tien().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btClear;
    private javax.swing.JButton btDocFile;
    private javax.swing.JButton btLuuFile;
    private javax.swing.JButton btNhapLai;
    private javax.swing.JButton btThemMoi;
    private javax.swing.JButton btThemMoi3;
    private javax.swing.JButton btThoat;
    private javax.swing.JButton btTimKiem;
    private javax.swing.JButton btnLamMoi;
    private javax.swing.JButton btnOTO;
    private javax.swing.JButton btnXeMay;
    private javax.swing.JButton btnXoa;
    private javax.swing.ButtonGroup buttonGroup1;
    private javax.swing.ButtonGroup buttonGroup2;
    private javax.swing.ButtonGroup buttonGroup3;
    private javax.swing.JComboBox<String> cbbLoaiXe;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel10;
    private javax.swing.JLabel jLabel11;
    private javax.swing.JLabel jLabel12;
    private javax.swing.JLabel jLabel13;
    private javax.swing.JLabel jLabel14;
    private javax.swing.JLabel jLabel15;
    private javax.swing.JLabel jLabel16;
    private javax.swing.JLabel jLabel17;
    private javax.swing.JLabel jLabel18;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JScrollPane jScrollPane2;
    private javax.swing.JTextArea jtThongBao;
    private javax.swing.JTextField removeID;
    private javax.swing.JTable tableHienThi;
    private javax.swing.JTextField timKiemHSX;
    private javax.swing.JTextField timkiemMauXe;
    private javax.swing.JTextField txtCongSuat;
    private javax.swing.JTextField txtGiaBan;
    private javax.swing.JTextField txtHangSanXuat;
    private javax.swing.JTextField txtID;
    private javax.swing.JTextField txtLDC;
    private javax.swing.JTextField txtLTrongTai;
    private javax.swing.JTextField txtMauXe;
    private javax.swing.JTextField txtNamSanXuat;
    private javax.swing.JTextField txtSoCho;
    // End of variables declaration//GEN-END:variables
}
